[package]
name = "codex-config-schema"
version = { workspace = true }
edition = "2024"

[dependencies]
anyhow = "1"
schemars = "0.8"
serde_json = "1"
codex-core = { path = "../core", features = ["json-schema"] }

[lints]
workspace = true

